/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mechio_speech_SAPI51_NativeSAPIEngine */

#ifndef _Included_org_mechio_speech_SAPI51_NativeSAPIEngine
#define _Included_org_mechio_speech_SAPI51_NativeSAPIEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mechio_speech_SAPI51_NativeSAPIEngine
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mechio_speech_SAPI51_NativeSAPIEngine_createEngine
  (JNIEnv *, jobject);

/*
 * Class:     org_mechio_speech_SAPI51_NativeSAPIEngine
 * Method:    shutdownEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mechio_speech_SAPI51_NativeSAPIEngine_shutdownEngine
  (JNIEnv *, jobject);

/*
 * Class:     org_mechio_speech_SAPI51_NativeSAPIEngine
 * Method:    addObserverNative
 * Signature: (Lorg/mechio/speech/TTSEngineObserver;)V
 */
JNIEXPORT void JNICALL Java_org_mechio_speech_SAPI51_NativeSAPIEngine_addObserverNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_mechio_speech_SAPI51_NativeSAPIEngine
 * Method:    speakNative
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_mechio_speech_SAPI51_NativeSAPIEngine_speakNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_mechio_speech_SAPI51_NativeSAPIEngine
 * Method:    cancelSpeechNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_mechio_speech_SAPI51_NativeSAPIEngine_cancelSpeechNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
